#!/bin/bash

cd ~/
#============= Installing dependencies ================
echo ubuntu | sudo apt -y update 
sudo apt -y upgrade
sudo apt -y install subversion cmake wget net-tools nano
#======================================================

#=========== Installing kernel modules ================
sudo apt -y install linux-headers-$(uname -r)
#======================================================

#=================== Networking ======================
cd ~/vbbu4
source du_net_conf
#======================================================

#================== Building OAI ======================
cd ~/vbbu4
source du_build
#======================================================

#================= Configuring OAI ====================
cd ~/vbbu4
source du_conf
#======================================================

#sudo ./cmake_targets/lte_build_oai/build/lte-softmodem -O ci-scripts/conf_files/du/enb.band7.tm1.25PRB.usrpb210.conf