#!/bin/bash

cd ~/
#============= Installing dependencies ================
echo ubuntu | sudo apt -y update 
sudo apt -y upgrade
sudo apt -y install git subversion cmake wget net-tools gedit
#======================================================

#=========== Installing kernel modules ================
sudo apt -y install linux-headers-$(uname -r)
#======================================================

#=================== Networking ======================
cd ~/enb
source enb_net_conf
#======================================================

#================== Building OAI ======================
cd ~/enb
source enb_build
#======================================================

#================= Configuring OAI ====================
cd ~/enb
source enb_conf
#======================================================

#./cmake_targets/lte_build_oai/build/lte-softmodem -O ci-scripts/conf_files/enb/enb.band7.tm1.25PRB.usrpb210.conf