#!/bin/bash
source enb_params
PREFIX=$HOME'/openairinterface5g/ci-scripts/conf_files/enb_enb.band7.tm1.25PRB.usrpb210.conf'
cp $HOME'/openairinterface5g/ci-scripts/conf_files/enb.band7.tm1.25PRB.usrpb210.conf' $PREFIX

#================== MME parameters ====================
sed -i -e "s|CI_MME_IP_ADDR|$mme_ip|g" $PREFIX
#======================================================

#================ NETWORK_INTERFACES ==================
sed -i '/ENB_INTERFACE_NAME_FOR_S1_MME/c\        ENB_INTERFACE_NAME_FOR_S1_MME            = "'$enb_if_s1c'";' $PREFIX
sed -i '/ENB_IPV4_ADDRESS_FOR_S1_MME/c\        ENB_IPV4_ADDRESS_FOR_S1_MME              = "'$enb_ip_s1c'";' $PREFIX
sed -i '/ENB_INTERFACE_NAME_FOR_S1U/c\        ENB_INTERFACE_NAME_FOR_S1U               = "'$enb_if_s1u'";' $PREFIX
sed -i '/ENB_IPV4_ADDRESS_FOR_S1U/c\        ENB_IPV4_ADDRESS_FOR_S1U                 = "'$enb_ip_s1u'";' $PREFIX
sed -i '/ENB_PORT_FOR_S1U/c\        ENB_PORT_FOR_S1U                         = "'$enb_port_s1u'";' $PREFIX
sed -i '/ENB_IPV4_ADDRESS_FOR_X2C/c\        ENB_IPV4_ADDRESS_FOR_X2C                 = "'$enb_ip_x2c'";' $PREFIX
sed -i '/ENB_PORT_FOR_X2C/c\       ENB_PORT_FOR_X2C                         = "'$enb_port_x2c'";' $PREFIX
#======================================================
