#!/bin/bash
#source enb_params
lxc_name=enb1
PREFIX='/var/lib/lxc/'$lxc_name'/config'
echo $PREFIX
#sudo ip route add $mme_ip via $host_ip_address dev $host_if_name #adding route to S1C interface
#sudo ip route add $spgw_ip via $host_ip_address dev $host_if_name #adding route to S1U interface

sudo lxc-create -t download -n $lxc_name -- -d ubuntu -r bionic -a amd64
#sudo lxc-create -t download -n $lxc_name -- -d ubuntu -r xenial -a amd64
echo -e  'lxc.cgroup.devices.allow = c 189:* rwm' | sudo -s tee -a $PREFIX
echo -e  'lxc.mount.entry = /dev/bus/usb dev/bus/usb none bind,optional,create=dir' | sudo -s tee -a $PREFIX
sudo lxc-start -n $lxc_name -d
sudo -s lxc-attach -n $lxc_name -- passwd ubuntu
