#!/bin/bash
sudo modprobe sctp #allow sctp flows
epc_host_ip=192.168.209.2
#mme_ip=192.168.247.102
spgw_ip=192.168.248.159

host_if_name=eno1
lxc_if_name=lxcbr0
lxc_ip=10.0.3.1
du_ip_s1c=192.168.209.40
du_ip_s1u=192.168.248.40


#=================== Route to eNB =====================
#adding route to EPC S1C interface
#sudo ip route add $mme_ip via $epc_host_ip dev $host_if_name
#adding route to EPC S1U interface
sudo ip route add $spgw_ip via $epc_host_ip dev $host_if_name
#======================================================


#=================== Route to EPC =====================
#adding route to eNB S1C interface
sudo ip route add $du_ip_s1c via $lxc_ip dev $lxc_if_name
#adding route to eNB S1U interface
sudo ip route add $du_ip_s1u via $lxc_ip dev $lxc_if_name
#======================================================
